### ISSUE TITLE
Example of calling the OpenAPI path

### ISSUE THREAD

**Issue by nojaf** [fsprojects/OpenAPITypeProvider#18]
Hello, 

I just tested this wonderful typeProvider and I'm able to create my JSON very nicely.
But I'm a bit confused what to do now.
Does this TP also expose functions to call the actual API? Or do I need to do that part myself?
If so, any samples or best practices on that?

Many thanks,

Florian

**Comment by Dzoukr** [comment]
Hello Florian,

this TP was designed to be used on server side providing API based on existing specification. Typical usage is to have it in Giraffe checking requests are coming in expected form (Schema) and replying back with schema again.

To make HTTP calls based on specification is the "other side" (client) and you should look at https://github.com/fsprojects/SwaggerProvider

**Comment by nojaf** [comment]
Hello Roman,

Thanks for clearing this up. I'm more looking for something like https://github.com/Szer/GiraffeGenerator I think.
