### ISSUE TITLE
Invite to move to fsprojects

### ISSUE THREAD

**Issue by dsyme** [fsprojects/OpenAPITypeProvider#4]
Hi @Dzoukr!

Amazing work :)

Just to say there is an open invitation to move this to http://github.com/fsprojects should you wish.  The main advantage is that there is a backup maintainer (can help make the project live a long time), and it can help attracting attention and raising visibility

Cheers!
Don

**Comment by Dzoukr** [comment]
Hi @dsyme,

thank you very much. That would be big honor for me (I love fsprojects)! What should I do next?

Cheers,
Roman

**Comment by dsyme** [comment]
I think you can just transfer directly in, give it a go. You will have to adjust urls of course after, and make sure you are listed as project admin.

Or else make me an admin here and I'll transfer it for you

**Comment by Dzoukr** [comment]
I got an error:
`You don’t have the permission to create repositories on fsprojects`

So I sent you an invitation and you can transfer it, please.

**Comment by dsyme** [comment]
> So I sent you an invitation and you can transfer it, please.


You need to make me admin I think

**Comment by Dzoukr** [comment]
It seems it is not possible for personal accounts - you can be collaborator only. :( Can you add me please to fsprojects organization and I'll transfer ownership to fsprojects?

**Comment by dsyme** [comment]
Ah ok

**Comment by dsyme** [comment]
I think you have to be a member of the "fsprojects" organization to create repos.  I've sent you an invitation.  Accept it and try to transfer again, thx

**Comment by Dzoukr** [comment]
Aaaaand done. Thanks @dsyme!
