### ISSUE TITLE
openapitypeprovider\1.5.1\lib\netstandard2.0\OpenAPITypeProvider.dll cannot be loaded

### ISSUE THREAD

**Issue by ctaggart** [fsprojects/OpenAPITypeProvider#6]
I'm a bit confused why I'm getting this TypeProvider error. I've got the latest Visual Studio 15.8.7 installed.

>Severity	Code	Description	Project	File	Line	Suppression State
Error	FS3031	The type provider 'C:\Users\taggac\.nuget\packages\openapitypeprovider\1.5.1\lib\netstandard2.0\OpenAPITypeProvider.dll' reported an error: Assembly attribute 'TypeProviderAssemblyAttribute' refers to a designer assembly 'C:\Users\taggac\.nuget\packages\openapitypeprovider\1.5.1\lib\netstandard2.0\OpenAPITypeProvider.dll' which cannot be loaded or doesn't exist. Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.	RegisterDeadboltClients	C:\Users\taggac\coreservices\RegisterDeadboltClients\FSC	1	Active

![image](https://user-images.githubusercontent.com/80104/46756898-2d2ac480-cc8e-11e8-8951-6606e1326daa.png)

**Comment by ctaggart** [comment]
`dotnet build` works. I wish F# type providers worked on dotnet core during design time in an editor. Here is the error from Ionide:

![image](https://user-images.githubusercontent.com/80104/46774370-b3afc800-ccc7-11e8-9e83-7e24ccc4b4f9.png)

My fsproj is:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="4.5.2" />
    <PackageReference Include="OpenAPITypeProvider" Version="1.5.0" />
  </ItemGroup>
</Project>
```

**Comment by ctaggart** [comment]
F# Type Provider Design-Time Components appears to still have troubles with dotnet core. Here are my notes from looking around:

> Currently, host tools look for TPDTC DLLs alongside the TPRTC DLL.
However, today, for a TPDTC to be .NET Standard 2.0, it must be loadable into host tools using .NET Framework 4.6.1 or Mono 5.x, the most common platforms for execution of F# tooling. Because .NET Framework 4.6.1 doesn't fully support .NET Standard 2.0, this can only be done if the TPDTC ships alongside some facade DLLs. Currently the following facade DLLs are needed alongside the TPDTC:
https://github.com/fsprojects/FSharp.TypeProviders.SDK#making-a-net-standard-20-tpdtc

F# Tooling RFC FST-1003 - Loading Type Provider Design-Time Components into F# Tooling
https://github.com/fsharp/fslang-design/blob/master/tooling/FST-1003-loading-type-provider-design-time-components.md

I think there are still unresolved problems https://github.com/Microsoft/visualfsharp/issues/3303#issuecomment-409708328

**Comment by dsyme** [comment]
If you author type providers with dependencies you should use the exact structure used by the TPSDK template 

    dotnet new -i FSharp.TypeProviders.Templates
    dotnet new typeprovider -n LemonadeProvider -lang F#

1. this has separate TPDTC and TPRTC
2. the nuget package is laid out correctly, including placing dependencies of the TPDTC into the TPDTC folder in the nuget
3. The magic flag is passed to allow dependency loading here https://github.com/fsprojects/FSharp.TypeProviders.SDK/blob/master/templates/content/basic/src/MyProvider.DesignTime/MyProvider.DesignTime.fs#L20

**Comment by Dzoukr** [comment]
@ctaggart FYI I still working on it, I got build already running, but fighting with `The design-time type 'OpenAPITypeProvider.ObjectValue' utilized by a type provider was not found in the target reference assembly set` error. Got little bit stuck on it, so would appreciate any hint how to fix it.

**Comment by Dzoukr** [comment]
Hi @ctaggart, please, could you try this version and let me know?

https://www.nuget.org/packages/OpenAPITypeProvider/1.6.0-beta1

It's based on template mentioned by @dsyme and should hopefully fix all problems with dependencies. 🙏

**Comment by ctaggart** [comment]
Yay! It is working now. 🎉

**Comment by Dzoukr** [comment]
Thanks @ctaggart! Going to release new full version soon, meanwhile stick with beta. Thanks!

**Comment by ctaggart** [comment]
Enjoy your weekend @Dzoukr! I'll be back on Tuesday. This looks like a great start.
